services:
  postgres:
    restart: unless-stopped
    tty: true
    image: postgres
    ports:
      - 5454:5432
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    networks:
      - keycloak-playground-network
    volumes:
      - keycloak-playground-db:/var/lib/postgresql/data
  keycloak:
    restart: unless-stopped
    tty: true
    command:
      - start-dev
      - --http-port=8180
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
    image: quay.io/keycloak/keycloak:25.0.6
    ports:
      - 8182:8180
    depends_on:
      - postgres
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=super
    volumes:
      - ./providers/:/opt/keycloak/providers/
    networks:
      - keycloak-playground-network

networks:
  keycloak-playground-network:
    name: keycloak-playground-network

volumes:
  keycloak-playground-db:
    name: keycloak-playground-db