apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: keycloak
type: Opaque
data:
  # The value below is base64 encoded
  KEYCLOAK_ADMIN: <base64-encoded>
  KEYCLOAK_ADMIN_PASSWORD: <base64-encoded>
  DB_USERNAME: <base64-encoded>
  DB_PASSWORD: <base64-encoded>