apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 3
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
      containers:
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0
          args:
            - "--structured-logs"
            - "--port=5432"
            - "--credentials-file=/secrets/cloudsql/credentials.json"
            - "project-id:asia-southeast2:keycloak-db"
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        - name: keycloak
          image: asia-southeast2-docker.pkg.dev/project-id/project-id/keycloak:latest
          args:
            - "start"
          env:
          - name: KC_HTTP_ENABLED
            value: "true"
          - name: KC_HOSTNAME_STRICT
            value: "true"
          - name: KC_HOSTNAME
            value: sso.domain.tld
          - name: KC_HOSTNAME_ADMIN
            value: iam.domain.tld
          - name: KC_HEALTH_ENABLED
            value: "true"
          - name: KC_PROXY
            value: "edge"
          - name: KEYCLOAK_ADMIN
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: KEYCLOAK_ADMIN
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: KEYCLOAK_ADMIN_PASSWORD
          - name: KC_DB
            value: "postgres"
          - name: KC_DB_URL
            value: "jdbc:postgresql://localhost:5432/keycloak"
          - name: KC_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: DB_USERNAME
          - name: KC_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-secret
                key: DB_PASSWORD
          - name: KC_FEATURES
            value: token-exchange,admin-fine-grained-authz,account-api
          - name: KC_CACHE
            value: "ispn"
          - name: KC_CACHE_STACK
            value: "kubernetes"
          - name: JAVA_OPTS_APPEND
            value: "-Djgroups.dns.query=keycloak-discovery.keycloak.svc.cluster.local"
          - name: JAVA_OPTS
            value: "-Xms512m -Xmx1024m"
          envFrom:
            - secretRef:
                name: keycloak-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          ports:
          - name: http
            containerPort: 8080
          - name: jgroups-bind
            containerPort: 7800
          - name: jgroups-fd
            containerPort: 57800

