apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
type: Opaque
data:
  # The value below is base64 encoded
  password: <base64-encoded>
  username: <base64-encoded>
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: keycloak
  name: keycloak-preconfigured-admin
  namespace: keycloak
type: kubernetes.io/basic-auth
data:
  # The value below is base64 encoded
  password: YWRtaW4= # admin by default
  username: YWRtaW4= # admin